### ISSUE TITLE
"loginWithService is not a function" @2.0.0

### ISSUE THREAD

**Issue by cneuro** [PoBuchi/meteor-accounts-linkedin#22]
Hi there,

after updating to 2.0.0 alongside Meteor 1.4.3.1, it seems like an ID somewhere isn't set properly for the accounts-core package to execute `loginWithService()`.

Interestingly enough, downgrading to 1.3.1 works once again without a hitch, even with Meteor 1.4.3.1.

EDIT: Logging in works again by downgrade, but logging out doesn't - there is no error. Is this just me?

![mainerror](https://cloud.githubusercontent.com/assets/2691584/23516808/8d82b0e8-ff6e-11e6-92e3-303b35e7409b.PNG)
![sourceerror](https://cloud.githubusercontent.com/assets/2691584/23516814/92fc6f46-ff6e-11e6-9355-38e05fab4d8e.PNG)

**Comment by PoBuchi** [comment]
@cneuro Yes, noticed:)

**Comment by PoBuchi** [comment]
Published pauli:accounts-linkedin@2.1.0.

**Comment by cneuro** [comment]
Hiya, thanks for your quick reply. Unfortunately, I'm still getting the exact same issue with 2.1.1. It's still fine in 1.3.1 (is a new version even needed?).

Also, is it normal that I need to force the update explicitly with `meteor add pauli:accounts-linkedin@2.1.1` instead of it just doing it automatically via `meteor update`?

**Comment by PoBuchi** [comment]
@cneuro [Meteor docs](http://docs.meteor.com/api/accounts.html),
use Meteor.loginWithLinkedIn

**Comment by ddaydd** [comment]
Hello,
I have the same error and Meteor.loginWithLinkedIn don't work. this package is always maintained?
the Meteor docs do not mention anything about linkedin.

thanks
